In [6]:
import pandas
from pandas import Series, DataFrame
from IPython.display import display, HTML

Read Source Data

In [39]:
# Read Character data

delimiter = ' \+\+\+\$\+\+\+ '
character_headers = ['character_id', 'character_name', 'movie_id', 'movie_title','gender','position_in_credit']
character_df = pandas.read_csv('../../data/cornell_corpus/movie_characters_metadata.txt',delimiter=delimiter,names=character_headers)

/Users/shuhanLin/anaconda/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [40]:
display(character_df)

,character_id,character_name,movie_id,movie_title,gender,position_in_credit
0,u0,BIANCA,m0,10 things i hate about you,f,4
1,u1,BRUCE,m0,10 things i hate about you,?,?
2,u2,CAMERON,m0,10 things i hate about you,m,3
3,u3,CHASTITY,m0,10 things i hate about you,?,?
4,u4,JOEY,m0,10 things i hate about you,m,6
5,u5,KAT,m0,10 things i hate about you,f,2
6,u6,MANDELLA,m0,10 things i hate about you,f,7
7,u7,MICHAEL,m0,10 things i hate about you,m,5
8,u8,MISS PERKY,m0,10 things i hate about you,?,?
9,u9,PATRICK,m0,10 things i hate about you,m,1
10,u10,SHARON,m0,10 things i hate about you,?,?
11,u11,WALTER,m0,10 things i hate about you,m,9
12,u12,ALONSO,m1,1492: conquest of paradise,?,?
13,u13,AROJAZ,m1,1492: conquest of paradise,?,?
14,u14,BEATRIX,m1,1492: conquest of paradise,?,?
15,u15,BOBADILLA,m1,1492: conquest of paradise,?,?
16,u16,COLUMBUS,m1,1492: conquest of paradise,m,1
17,u17,FERNANDO,m1,1492: conquest of paradise,?,?
18,u18,ISABEL,m1,1492: conquest of paradise,?,?
19,u19,MARCHENA,m1,1492: conquest of paradise,m,6
20,u20,MENDEZ,m1,1492: conquest of paradise,?,?
21,u21,MOXICA,m1,1492: conquest of paradise,?,?
22,u22,PINZON,m1,1492: conquest of paradise,?,?
23,u23,SAILOR,m1,1492: conquest of paradise,?,?
24,u24,SANCHEZ,m1,1492: conquest of paradise,?,?
25,u25,UTAPAN,m1,1492: conquest of paradise,?,?
26,u26,CUTLER,m2,15 minutes,m,?
27,u27,DAPHNE,m2,15 minutes,f,8
28,u28,DUFFY,m2,15 minutes,?,?
29,u29,EDDIE,m2,15 minutes,m,1
...,...,...,...,...,...,...
9005,u9005,KELLY,m614,x-men,?,?
9006,u9006,LOGAN,m614,x-men,?,?
9007,u9007,MAGNETO,m614,x-men,?,?
9008,u9008,SABRETOOTH,m614,x-men,?,?
9009,u9009,STORM,m614,x-men,?,?
9010,u9010,XAVIER,m614,x-men,?,?
9011,u9011,ANASTASIA,m615,young frankenstein,?,?
9012,u9012,BURGOMEISTER,m615,young frankenstein,?,?
9013,u9013,CARLSON,m615,young frankenstein,?,?
9014,u9014,CORNELIUS WALDMAN,m615,young frankenstein,?,?
9015,u9015,ELIZABETH,m615,young frankenstein,f,25
9016,u9016,FRAU BLUCHER,m615,young frankenstein,?,?
9017,u9017,FREDDY,m615,young frankenstein,M,?
9018,u9018,HERR FALKSTEIN,m615,young frankenstein,?,?
9019,u9019,IGOR,m615,young frankenstein,m,3
9020,u9020,INGA,m615,young frankenstein,f,5
9021,u9021,MAITRE D',m615,young frankenstein,?,?
9022,u9022,MEDICAL STUDENT,m615,young frankenstein,m,9
9023,u9023,MONSTER,m615,young frankenstein,?,?
9024,u9024,OLD VIOLINIST,m615,young frankenstein,?,?
9025,u9025,BLOOMFIELD,m616,zulu dawn,?,?
9026,u9026,BOY-PULLEN,m616,zulu dawn,?,?
9027,u9027,CHELMSFORD,m616,zulu dawn,?,?
9028,u9028,COGHILL,m616,zulu dawn,?,?
9029,u9029,CREALOCK,m616,zulu dawn,?,?
9030,u9030,DURNFORD,m616,zulu dawn,?,?
9031,u9031,MELVILL,m616,zulu dawn,?,?
9032,u9032,NORRIS-NEWMAN,m616,zulu dawn,?,?
9033,u9033,STUART SMITH,m616,zulu dawn,?,?
9034,u9034,VEREKER,m616,zulu dawn,?,?

In [41]:
# Read movie data

movie_headers = ['movie_id', 'movie_title','movie_year','IMDB_rating','IMDB_note','genres']
movie_df = pandas.read_csv('../../data/cornell_corpus/movie_titles_metadata.txt',delimiter=delimiter,names=movie_headers)

/Users/shuhanLin/anaconda/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [42]:
display(movie_df)

,movie_id,movie_title,movie_year,IMDB_rating,IMDB_note,genres
0,m0,10 things i hate about you,1999,6.9,62847,"['comedy', 'romance']"
1,m1,1492: conquest of paradise,1992,6.2,10421,"['adventure', 'biography', 'drama', 'history']"
2,m2,15 minutes,2001,6.1,25854,"['action', 'crime', 'drama', 'thriller']"
3,m3,2001: a space odyssey,1968,8.4,163227,"['adventure', 'mystery', 'sci-fi']"
4,m4,48 hrs.,1982,6.9,22289,"['action', 'comedy', 'crime', 'drama', 'thrill..."
5,m5,the fifth element,1997,7.5,133756,"['action', 'adventure', 'romance', 'sci-fi', '..."
6,m6,8mm,1999,6.3,48212,"['crime', 'mystery', 'thriller']"
7,m7,a nightmare on elm street 4: the dream master,1988,5.2,13590,"['fantasy', 'horror', 'thriller']"
8,m8,a nightmare on elm street: the dream child,1989,4.7,11092,"['fantasy', 'horror', 'thriller']"
9,m9,the atomic submarine,1959,4.9,513,"['sci-fi', 'thriller']"
10,m10,affliction,1997,6.9,7252,"['drama', 'mystery', 'thriller']"
11,m11,air force one,1997,6.3,61978,"['action', 'drama', 'thriller']"
12,m12,airplane ii: the sequel,1982,5.8,15210,"['comedy', 'romance', 'sci-fi']"
13,m13,airplane!,1980,7.8,57692,"['comedy', 'romance']"
14,m14,alien nation,1988,6.1,5590,"['crime', 'drama', 'sci-fi', 'thriller']"
15,m15,aliens,1986,8.5,173518,"['action', 'sci-fi', 'thriller']"
16,m16,amadeus,1984,8.4,99138,"['biography', 'drama', 'music']"
17,m17,an american werewolf in london,1981,7.5,24443,"['horror', 'romance']"
18,m18,american madness,1932,7.4,702,['drama']
19,m19,american outlaws,2001,5.7,7425,"['action', 'western']"
20,m20,american psycho,2000,7.4,101357,"['drama', 'thriller']"
21,m21,antitrust,2001,6.0,16453,"['drama', 'thriller']"
22,m22,austin powers: international man of mystery,1997,7.1,75240,"['action', 'adventure', 'comedy', 'crime']"
23,m23,the avengers,1998,3.4,21519,"['action', 'adventure', 'thriller']"
24,m24,bachelor party,1984,5.9,14050,"['comedy', 'romance']"
25,m25,backdraft,1991,6.6,28541,"['action', 'crime', 'drama', 'mystery', 'thril..."
26,m26,bad lieutenant,1992,6.9,13908,"['crime', 'drama']"
27,m27,bamboozled,2000,6.3,5995,"['comedy', 'drama', 'music']"
28,m28,barry lyndon,1975,8.1,40622,"['drama', 'romance', 'war']"
29,m29,basic,2003,6.3,26295,"['crime', 'drama', 'mystery', 'thriller']"
...,...,...,...,...,...,...
587,m587,twelve monkeys,1995,8.1,173320,"['mystery', 'sci-fi', 'thriller']"
588,m588,u-turn,1973,5.8,37,['drama']
589,m589,u turn,1997,6.7,25388,"['crime', 'drama', 'thriller']"
590,m590,unbreakable,2000,7.3,98767,"['drama', 'fantasy', 'mystery', 'thriller']"
591,m591,unforgiven,1992,8.3,101270,"['drama', 'western']"
592,m592,the usual suspects,1995,8.7,272137,"['crime', 'mystery', 'thriller']"
593,m593,verdict,1974,5.7,135,['drama']
594,m594,vertigo,1958,8.6,93524,"['crime', 'mystery', 'romance', 'thriller']"
595,m595,very bad things,1998,6.0,22977,"['comedy', 'crime', 'thriller']"
596,m596,viridiana,1961,8.2,6288,['drama']
597,m597,virtuosity,1995,5.3,11191,"['action', 'crime', 'sci-fi', 'thriller']"
598,m598,wag the dog,1997,7.1,36448,"['comedy', 'drama']"
599,m599,wall street,1987,7.3,39082,"['crime', 'drama']"
600,m600,waxwork,1988,6.0,2596,"['comedy', 'fantasy', 'horror']"
601,m601,what lies beneath,2000,6.5,46195,"['drama', 'horror', 'mystery', 'thriller']"
602,m602,what women want,2000,6.3,55269,"['comedy', 'fantasy', 'romance']"
603,m603,the witching hour,1996,6.5,69,"['documentary', 'short']"
604,m604,white angel,1994,4.4,99,"['drama', 'thriller']"
605,m605,who's your daddy?,2003/I,4.5,2267,['comedy']
606,m606,wild things,1998,6.6,40523,"['crime', 'mystery', 'thriller']"
607,m607,wild wild west,1999,4.3,54943,"['action', 'western', 'comedy', 'sci-fi']"
608,m608,willow,1988,7.1,33506,"['action', 'adventure', 'drama', 'fantasy', 'r..."
609,m609,witness,1985,7.6,30705,"['drama', 'romance', 'thriller']"
610,m610,the wizard of oz,1939,8.3,104873,"['adventure', 'family', 'fantasy', 'musical']"
611,m611,the world is not enough,1999,6.3,60047,"['action', 'adventure', 'thriller']"
612,m612,watchmen,2009,7.8,135229,"['action', 'crime', 'fantasy', 'mystery', 'sci..."
613,m613,xxx,2002,5.6,53505,"['action', 'adventure', 'crime']"
614,m614,x-men,2000,7.4,122149,"['action', 'sci-fi']"
615,m615,young frankenstein,1974,8.0,57618,"['comedy', 'sci-fi']"
616,m616,zulu dawn,1979,6.4,1911,"['action', 'adventure', 'drama', 'history', 'w..."

In [43]:
#movie lines data

movie_sentence_headers = ['line_id', 'character_id','movie_id','character_name','text']
movie_sentence_df = pandas.read_csv('../../data/cornell_corpus/movie_lines.txt',delimiter=delimiter,names=movie_sentence_headers)

/Users/shuhanLin/anaconda/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [44]:
display(movie_sentence_df)

,line_id,character_id,movie_id,character_name,text
0,L1045,u0,m0,BIANCA,They do not!
1,L1044,u2,m0,CAMERON,They do to!
2,L985,u0,m0,BIANCA,I hope so.
3,L984,u2,m0,CAMERON,She okay?
4,L925,u0,m0,BIANCA,Let's go.
5,L924,u2,m0,CAMERON,Wow
6,L872,u0,m0,BIANCA,Okay -- you're gonna need to learn how to lie.
7,L871,u2,m0,CAMERON,No
8,L870,u0,m0,BIANCA,I'm kidding. You know how sometimes you just ...
9,L869,u0,m0,BIANCA,Like my fear of wearing pastels?
10,L868,u2,m0,CAMERON,"The ""real you""."
11,L867,u0,m0,BIANCA,What good stuff?
12,L866,u2,m0,CAMERON,I figured you'd get to the good stuff eventually.
13,L865,u2,m0,CAMERON,Thank God! If I had to hear one more story ab...
14,L864,u0,m0,BIANCA,"Me. This endless ...blonde babble. I'm like, ..."
15,L863,u2,m0,CAMERON,What crap?
16,L862,u0,m0,BIANCA,do you listen to this crap?
17,L861,u2,m0,CAMERON,No...
18,L860,u0,m0,BIANCA,"Then Guillermo says, ""If you go any lighter, y..."
19,L699,u2,m0,CAMERON,You always been this selfish?
20,L698,u0,m0,BIANCA,But
21,L697,u2,m0,CAMERON,Then that's all you had to say.
22,L696,u0,m0,BIANCA,"Well, no..."
23,L695,u2,m0,CAMERON,"You never wanted to go out with 'me, did you?"
24,L694,u0,m0,BIANCA,I was?
25,L693,u2,m0,CAMERON,"I looked for you back at the party, but you al..."
26,L663,u0,m0,BIANCA,Tons
27,L662,u2,m0,CAMERON,Have fun tonight?
28,L578,u2,m0,CAMERON,I believe we share an art instructor
29,L577,u0,m0,BIANCA,You know Chastity?
...,...,...,...,...,...
304683,L666460,u9029,m616,CREALOCK,The only reports of enemy activity have come f...
304684,L666385,u9027,m616,CHELMSFORD,"Our runners bare his dispatches, do they not?"
304685,L666384,u9029,m616,CREALOCK,"Er, called Noggs, Sir Actual name is Norris-Ne..."
304686,L666383,u9027,m616,CHELMSFORD,What's that strange name the newspaper chap's ...
304687,L666252,u9027,m616,CHELMSFORD,But will they make good use of them?
304688,L666251,u9029,m616,CREALOCK,Yes. I see you've issued each of them with a M...
304689,L666502,u9033,m616,STUART SMITH,"Right. Bombardier, to me please."
304690,L666501,u9028,m616,COGHILL,"Well, fed or hungry, Pulleine wants them in po..."
304691,L666500,u9033,m616,STUART SMITH,"Well, my horses are feeding, as you may observ..."
304692,L666499,u9028,m616,COGHILL,How quickly can you move your artillery forward?
304693,L666498,u9033,m616,STUART SMITH,Yes.
304694,L666497,u9028,m616,COGHILL,Stuart?
304695,L666576,u9031,m616,MELVILL,Keep steady. You're the best shots of the Twen...
304696,L666575,u9028,m616,COGHILL,Choose your targets men. That's right Watch th...
304697,L666327,u9031,m616,MELVILL,ft could be you flatter yourself CoghilL It's ...
304698,L666326,u9028,m616,COGHILL,Well that one. The one who keeps looking at me.
304699,L666325,u9031,m616,MELVILL,Which one?
304700,L666324,u9028,m616,COGHILL,Do you think she might be interested in someone?
304701,L666264,u9031,m616,MELVILL,Well that's typical of Her Majesty's army. App...
304702,L666263,u9028,m616,COGHILL,Um. There are rumours that my Lord Chelmsford ...
304703,L666262,u9031,m616,MELVILL,Lighting COGHILL' 5 cigar: Our good Colonel Du...
304704,L666522,u9034,m616,VEREKER,So far only their scouts. But we have had repo...
304705,L666521,u9030,m616,DURNFORD,"And I assure you, you do not In fact I'd be ob..."
304706,L666520,u9034,m616,VEREKER,"Well I assure you, Sir, I have no desire to cr..."
304707,L666372,u9034,m616,VEREKER,I think Chelmsford wants a good man on the bor...
304708,L666371,u9030,m616,DURNFORD,Lord Chelmsford seems to want me to stay back ...
304709,L666370,u9034,m616,VEREKER,I'm to take the Sikali with the main column to...
304710,L666369,u9030,m616,DURNFORD,"Your orders, Mr Vereker?"
304711,L666257,u9030,m616,DURNFORD,"Good ones, yes, Mr Vereker. Gentlemen who can ..."
304712,L666256,u9034,m616,VEREKER,Colonel Durnford... William Vereker. I hear yo...

In [60]:
# movie dialog text

movie_dialog_headers = ['first_character_id', 'second_character_id','movie_id','dialog_list']
movie_dialog_df = pandas.read_csv('../../data/cornell_corpus/movie_conversations.txt',delimiter=delimiter,names=movie_dialog_headers)

/Users/shuhanLin/anaconda/envs/tensorflow/lib/python3.6/site-packages/ipykernel/__main__.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [61]:
display(movie_dialog_df)

,first_character_id,second_character_id,movie_id,dialog_list
0,u0,u2,m0,"['L194', 'L195', 'L196', 'L197']"
1,u0,u2,m0,"['L198', 'L199']"
2,u0,u2,m0,"['L200', 'L201', 'L202', 'L203']"
3,u0,u2,m0,"['L204', 'L205', 'L206']"
4,u0,u2,m0,"['L207', 'L208']"
5,u0,u2,m0,"['L271', 'L272', 'L273', 'L274', 'L275']"
6,u0,u2,m0,"['L276', 'L277']"
7,u0,u2,m0,"['L280', 'L281']"
8,u0,u2,m0,"['L363', 'L364']"
9,u0,u2,m0,"['L365', 'L366']"
10,u0,u2,m0,"['L367', 'L368']"
11,u0,u2,m0,"['L401', 'L402', 'L403']"
12,u0,u2,m0,"['L404', 'L405', 'L406', 'L407']"
13,u0,u2,m0,"['L575', 'L576']"
14,u0,u2,m0,"['L577', 'L578']"
15,u0,u2,m0,"['L662', 'L663']"
16,u0,u2,m0,"['L693', 'L694', 'L695']"
17,u0,u2,m0,"['L696', 'L697', 'L698', 'L699']"
18,u0,u2,m0,"['L860', 'L861']"
19,u0,u2,m0,"['L862', 'L863', 'L864', 'L865']"
20,u0,u2,m0,"['L866', 'L867', 'L868', 'L869']"
21,u0,u2,m0,"['L870', 'L871', 'L872']"
22,u0,u2,m0,"['L924', 'L925']"
23,u0,u2,m0,"['L984', 'L985']"
24,u0,u2,m0,"['L1044', 'L1045']"
25,u0,u3,m0,"['L49', 'L50', 'L51']"
26,u0,u3,m0,"['L571', 'L572', 'L573']"
27,u0,u3,m0,"['L579', 'L580']"
28,u0,u3,m0,"['L595', 'L596', 'L597']"
29,u0,u3,m0,"['L598', 'L599', 'L600']"
...,...,...,...,...
83067,u9019,u9020,m615,"['L666158', 'L666159']"
83068,u9019,u9020,m615,"['L666160', 'L666161']"
83069,u9019,u9020,m615,"['L666166', 'L666167']"
83070,u9019,u9020,m615,"['L666168', 'L666169']"
83071,u9021,u9023,m615,"['L665987', 'L665988', 'L665989', 'L665990', '..."
83072,u9021,u9023,m615,"['L665992', 'L665993']"
83073,u9021,u9023,m615,"['L665994', 'L665995', 'L665996', 'L665997']"
83074,u9025,u9026,m616,"['L666361', 'L666362', 'L666363', 'L666364']"
83075,u9025,u9026,m616,"['L666365', 'L666366', 'L666367', 'L666368']"
83076,u9025,u9026,m616,"['L666462', 'L666463']"
83077,u9027,u9032,m616,"['L666388', 'L666389', 'L666390', 'L666391', '..."
83078,u9027,u9032,m616,"['L666503', 'L666504', 'L666505']"
83079,u9027,u9030,m616,"['L666246', 'L666247', 'L666248']"
83080,u9027,u9030,m616,"['L666249', 'L666250']"
83081,u9027,u9030,m616,"['L666357', 'L666358']"
83082,u9027,u9030,m616,"['L666480', 'L666481', 'L666482']"
83083,u9027,u9030,m616,"['L666483', 'L666484']"
83084,u9027,u9030,m616,"['L666487', 'L666488']"
83085,u9027,u9029,m616,"['L666251', 'L666252']"
83086,u9027,u9029,m616,"['L666383', 'L666384', 'L666385']"
83087,u9027,u9029,m616,"['L666460', 'L666461']"
83088,u9027,u9029,m616,"['L666485', 'L666486']"
83089,u9027,u9029,m616,"['L666546', 'L666547']"
83090,u9028,u9033,m616,"['L666497', 'L666498', 'L666499', 'L666500', '..."
83091,u9028,u9031,m616,"['L666262', 'L666263', 'L666264']"
83092,u9028,u9031,m616,"['L666324', 'L666325', 'L666326', 'L666327']"
83093,u9028,u9031,m616,"['L666575', 'L666576']"
83094,u9030,u9034,m616,"['L666256', 'L666257']"
83095,u9030,u9034,m616,"['L666369', 'L666370', 'L666371', 'L666372']"
83096,u9030,u9034,m616,"['L666520', 'L666521', 'L666522']"

Data quality detection & Data cleaning

In [56]:
# This function is used to check the percentage of missing values in each column of dataframe

def check_null_percentage(df, field_list):
    if df is None:
        print('df does not exist')
        return
    
    if not field_list or len(field_list) == 0:
        print('field list does not exist or is empty')
        return
    
    percent_dic = {}
    for field in field_list:
        null_count =df[field].isnull().sum()
        total_count = len(df[field].index)
    
        if total_count == 0:
            percent =  '0%'
        else:
            percent = str(null_count / total_count * 100) + '%'
            
        percent_dic[field] = percent
        
    return percent_dic

In [62]:
# Null check for each dataframe

# character data frame
print(check_null_percentage(character_df, character_headers))

# movie data frame
print(check_null_percentage(movie_df, movie_headers))

# movie_sentence_frame
print(check_null_percentage(movie_sentence_df, movie_sentence_headers))

# movie_conversation_frame
print(check_null_percentage(movie_dialog_df, movie_dialog_headers))

{'character_id': '0.0%', 'character_name': '0.0221361372441%', 'movie_id': '0.0%', 'movie_title': '0.0%', 'gender': '0.0%', 'position_in_credit': '0.0%'}
{'movie_id': '0.0%', 'movie_title': '0.0%', 'movie_year': '0.0%', 'IMDB_rating': '0.0%', 'IMDB_note': '0.0%', 'genres': '0.0%'}
{'line_id': '0.0%', 'character_id': '0.0%', 'movie_id': '0.0%', 'character_name': '0.0141116394771%', 'text': '0.0876234358232%'}
{'first_character_id': '0.0%', 'second_character_id': '0.0%', 'movie_id': '0.0%', 'dialog_list': '0.0%'}